mutation saveClientMasterData($firstName: String $email: String) {
    saveClientMasterData(firstName: $firstName email: $email) {
        email
        firstName
        Id
        Message
        Message
    }
}
